### ISSUE TITLE
rc2nix error: setting outside of group: MenuBar=Disabled (RuntimeError)

### ISSUE THREAD

**Issue by RGBCube** [nix-community/plasma-manager#17]
I am getting this error while trying to run the `rc2nix` script:

```rb
./rc2nix:126:in `block (2 levels) in parse': /home/nixos/.config/dolphinrc: setting outside of group: MenuBar=Disabled (RuntimeError)
        from ./rc2nix:115:in `each'
        from ./rc2nix:115:in `block in parse'
        from ./rc2nix:114:in `open'
        from ./rc2nix:114:in `parse'
        from ./rc2nix:180:in `block in run'
        from ./rc2nix:176:in `each'
        from ./rc2nix:176:in `run'
        from ./rc2nix:266:in `<main>'
```

**Comment by CHN-beta** [comment]
same issue

**Comment by RGBCube** [comment]
it works fine when you remove the groupless setting though

**Comment by ShalokShalom** [comment]
Same for me. 

```
nix run github:pjones/plasma-manager
Traceback (most recent call last):
        8: from /nix/store/g8q4grnxyl32y2hxsx8gzflpvfxzxp7y-rc2nix.rb:266:in `<main>'
        7: from /nix/store/g8q4grnxyl32y2hxsx8gzflpvfxzxp7y-rc2nix.rb:176:in `run'
        6: from /nix/store/g8q4grnxyl32y2hxsx8gzflpvfxzxp7y-rc2nix.rb:176:in `each'
        5: from /nix/store/g8q4grnxyl32y2hxsx8gzflpvfxzxp7y-rc2nix.rb:180:in `block in run'
        4: from /nix/store/g8q4grnxyl32y2hxsx8gzflpvfxzxp7y-rc2nix.rb:114:in `parse'
        3: from /nix/store/g8q4grnxyl32y2hxsx8gzflpvfxzxp7y-rc2nix.rb:114:in `open'
        2: from /nix/store/g8q4grnxyl32y2hxsx8gzflpvfxzxp7y-rc2nix.rb:115:in `block in parse'
        1: from /nix/store/g8q4grnxyl32y2hxsx8gzflpvfxzxp7y-rc2nix.rb:115:in `each'
/nix/store/g8q4grnxyl32y2hxsx8gzflpvfxzxp7y-rc2nix.rb:126:in `block (2 levels) in parse': /home/cosmos/.config/dolphinrc: setting outside of group: MenuBar=Disabled (RuntimeError)
```

@RGBCube How do you mean that?

**Comment by RGBCube** [comment]
> Same for me. 
> 
> ```
> nix run github:pjones/plasma-manager
> Traceback (most recent call last):
>         8: from /nix/store/g8q4grnxyl32y2hxsx8gzflpvfxzxp7y-rc2nix.rb:266:in `<main>'
>         7: from /nix/store/g8q4grnxyl32y2hxsx8gzflpvfxzxp7y-rc2nix.rb:176:in `run'
>         6: from /nix/store/g8q4grnxyl32y2hxsx8gzflpvfxzxp7y-rc2nix.rb:176:in `each'
>         5: from /nix/store/g8q4grnxyl32y2hxsx8gzflpvfxzxp7y-rc2nix.rb:180:in `block in run'
>         4: from /nix/store/g8q4grnxyl32y2hxsx8gzflpvfxzxp7y-rc2nix.rb:114:in `parse'
>         3: from /nix/store/g8q4grnxyl32y2hxsx8gzflpvfxzxp7y-rc2nix.rb:114:in `open'
>         2: from /nix/store/g8q4grnxyl32y2hxsx8gzflpvfxzxp7y-rc2nix.rb:115:in `block in parse'
>         1: from /nix/store/g8q4grnxyl32y2hxsx8gzflpvfxzxp7y-rc2nix.rb:115:in `each'
> /nix/store/g8q4grnxyl32y2hxsx8gzflpvfxzxp7y-rc2nix.rb:126:in `block (2 levels) in parse': /home/cosmos/.config/dolphinrc: setting outside of group: MenuBar=Disabled (RuntimeError)
> ```
> 
> @RGBCube How do you mean that?

Delete the MenuBar=Disabled line, then it will work. Still weird that this isn't accounted for, tho

**Comment by ShalokShalom** [comment]
@pjones This is a default KDE setting. 
rc2nix currently fails at a vanilla configuration. 

@RGBCube 
> Delete the MenuBar=Disabled line, then it will work. Still weird that this isn't accounted for, tho

Thanks a lot. I enabled the menubar manually in Dolphin itself, and this does not solve it. The same error occurs again. 

The choice in Dolphin does not reflect a change at /.config/dolphinrc. 

And it is also without an annotated [Category], it is on top of the file, simply lonely sitting there.


![Screenshot_20231029_121443](https://github.com/pjones/plasma-manager/assets/6344099/bd8c087e-bd8c-4135-b796-922a47c78368)

When I remove it at the file directly, and then add it back with Dolphin, does it set it at the correct location. 
And it then has the correct annotation as well. 

![Screenshot_20231029_124655](https://github.com/pjones/plasma-manager/assets/6344099/3f205074-ab4a-4b0a-ad66-6ed82b8858f7)

This seems like some configuration issue from Nix/KDE maybe. 

Garuda does not seem to have this issue, but it is heavily themed out of the box. 
So not saying much. :)

**Comment by notjiatan** [comment]
@HeitorAugustoLN @toast003 @RGBCube @ShalokShalom 
Hi, I was wondering if any of you knew of a work around for this bug

I would like to add `MenuBar=Disabled` to my config file

**Comment by HeitorAugustoLN** [comment]
@notjiatan after #465 is done it should have support for settings without a group
