### ISSUE TITLE
Update flake.lock

### ISSUE THREAD

**Issue by Asqiir** [nix-community/plasma-manager#442]
I would like to update the `flake.lock` to get access to newer library functions, especially `lib.defaultTo` which has been (recently added)[https://github.com/NixOS/nixpkgs/pull/357681] and is now arrived in `nixos-unstable` (which is the branch we use afaict).

I created PR #441. I ran `nix flake udpate` on my fork of plasma-manager. There, `nix flake check` fails. (Log below, look also in the failed action.)

# Logs
```
❯ nix flake check
warning: Git tree '/home/me/workspace/plasma-manager' is dirty
warning: unknown flake output 'homeManagerModules'
error: builder for '/nix/store/1qb8fgcdc7z0kimlg1y20yydam75kily-vm-test-run-plasma-basic.drv' failed with exit code 1;
       last 25 log lines:
       > machine: waiting for unit home-manager-fake.service
       > cleanup
       > kill machine (pid 11)
       > qemu-system-x86_64: terminating on signal 15 from pid 8 (/nix/store/zv1kaq7f1q20x62kbjv6pfjygw5jmwl6-python3-3.12.7/bin/python3.12)
       > kill vlan (pid 9)
       > (finished: cleanup, in 0.03 seconds)
       > Traceback (most recent call last):
       >   File "/nix/store/p03rnikd33x3f0fj217kkqnccvg5cszq-nixos-test-driver-1.1/bin/.nixos-test-driver-wrapped", line 9, in <module>
       >     sys.exit(main())
       >              ^^^^^^
       >   File "/nix/store/p03rnikd33x3f0fj217kkqnccvg5cszq-nixos-test-driver-1.1/lib/python3.12/site-packages/test_driver/__init__.py", line 146, in main
       >     driver.run_tests()
       >   File "/nix/store/p03rnikd33x3f0fj217kkqnccvg5cszq-nixos-test-driver-1.1/lib/python3.12/site-packages/test_driver/driver.py", line 174, in run_tests
       >     self.test_script()
       >   File "/nix/store/p03rnikd33x3f0fj217kkqnccvg5cszq-nixos-test-driver-1.1/lib/python3.12/site-packages/test_driver/driver.py", line 166, in test_script
       >     exec(self.tests, symbols, None)
       >   File "<string>", line 4, in <module>
       >   File "/nix/store/p03rnikd33x3f0fj217kkqnccvg5cszq-nixos-test-driver-1.1/lib/python3.12/site-packages/test_driver/machine.py", line 375, in wait_for_unit
       >     retry(check_active, timeout)
       >   File "/nix/store/p03rnikd33x3f0fj217kkqnccvg5cszq-nixos-test-driver-1.1/lib/python3.12/site-packages/test_driver/machine.py", line 130, in retry
       >     if fn(False):
       >        ^^^^^^^^^
       >   File "/nix/store/p03rnikd33x3f0fj217kkqnccvg5cszq-nixos-test-driver-1.1/lib/python3.12/site-packages/test_driver/machine.py", line 365, in check_active
       >     raise Exception(
       > Exception: unit "home-manager-fake.service" is inactive and there are no pending jobs
       For full logs, run 'nix log /nix/store/1qb8fgcdc7z0kimlg1y20yydam75kily-vm-test-run-plasma-basic.drv'.
❯ nix log /nix/store/1qb8fgcdc7z0kimlg1y20yydam75kily-vm-test-run-plasma-basic.drv
warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/1qb8fgcdc7z0kimlg1y20yydam75kily-vm-test-run-plasma-basic.drv^*'
Machine state will be reset. To keep it, pass --keep-vm-state
start all VLans
start vlan
running vlan (pid 9; ctl /build/vde1.ctl)
(finished: start all VLans, in 0.01 seconds)
Test will time out and terminate in 3600 seconds
run the VM test script
additionally exposed symbols:
    machine,
    vlan1,
    start_all, test_script, machines, vlans, driver, log, os, create_machine, subtest, run_tests, join_all, retry, serial>
start all VMs
machine: starting vm
mke2fs 1.47.1 (20-May-2024)
machine: QEMU running (pid 11)
machine # Disk image do not exist, creating the virtualisation disk image...
machine # Formatting '/build/vm-state-machine/tmp.xyZ4hcQd4y', fmt=raw size=1073741824
machine # Discarding device blocks: done
machine # Creating filesystem with 262144 4k blocks and 65536 inodes
(finished: start all VMs, in 0.34 seconds)
machine # Filesystem UUID: 560500b7-cac4-4e9f-88cb-adb456b3a72b
machine: waiting for unit multi-user.target
machine: waiting for the VM to finish booting
machine # Superblock backups stored on blocks:
machine #       32768, 98304, 163840, 229376
machine # 
machine # Allocating group tables: done
machine # Writing inode tables: done
machine # Creating journal (8192 blocks): done
```

**Comment by Asqiir** [comment]
It turns out, services aren't automatically started anymore if they are not needed, presumably as an optimization.

`home-manager-$USER.service` is a system service when home-manager is installed as a module (as opposed to standalone). That is, waiting for this service fails.

Currently there is no option to force this service to start. Therefore I have removed the check.

@HeitorAugustoLN What is your opinion on this?

**Comment by HeitorAugustoLN** [comment]
I need to take a look at it.

**Comment by Asqiir** [comment]
what's the status?
(sorry if bumping is not the way to go)

**Comment by HeitorAugustoLN** [comment]
> what's the status? (sorry if bumping is not the way to go)

I am not sure yet, I am currently rewriting the plasma-manager scripts into rust, also making it an complete alternative to kconfig, so I haven't looked into it. And I am also planning to do some refactoring around the codebase. So it will probably take a while until I can look at it, since school is also taking quite of my time
